#ifndef PRODUCT_CONTROL_LOOP_CONFIG_H
#define PRODUCT_CONTROL_LOOP_CONFIG_H

#define CONTROL_LOOP_FREQUENCY_HZ				20000U
#define CONTROL_LOOP_PERIOD_S				(1.0f / (float)CONTROL_LOOP_FREQUENCY_HZ)

/* Current loop executes at the PWM/CurrentControl rate. */
#define CURRENT_LOOP_PERIOD_S       (CONTROL_LOOP_PERIOD_S)

/* All speed PI controllers and encoder velocity estimation run at 2 kHz. */
#define SPEED_LOOP_FREQUENCY_HZ     2000U
#if SPEED_LOOP_FREQUENCY_HZ == 0U
#error "SPEED_LOOP_FREQUENCY_HZ must be greater than zero"
#elif SPEED_LOOP_FREQUENCY_HZ > CONTROL_LOOP_FREQUENCY_HZ
#error "SPEED_LOOP_FREQUENCY_HZ must not exceed CONTROL_LOOP_FREQUENCY_HZ"
#elif (CONTROL_LOOP_FREQUENCY_HZ % SPEED_LOOP_FREQUENCY_HZ) != 0U
#error "SPEED_LOOP_FREQUENCY_HZ must divide CONTROL_LOOP_FREQUENCY_HZ exactly"
#endif
#define SPEED_LOOP_DIVIDER          (CONTROL_LOOP_FREQUENCY_HZ / SPEED_LOOP_FREQUENCY_HZ)
#define SPEED_LOOP_PERIOD_S         (1.0f / (float)SPEED_LOOP_FREQUENCY_HZ)

/* Position trajectory and impedance controller run at 1 kHz. */
#define POSITION_LOOP_FREQUENCY_HZ  1000U
#if POSITION_LOOP_FREQUENCY_HZ == 0U
#error "POSITION_LOOP_FREQUENCY_HZ must be greater than zero"
#elif POSITION_LOOP_FREQUENCY_HZ > CONTROL_LOOP_FREQUENCY_HZ
#error "POSITION_LOOP_FREQUENCY_HZ must not exceed CONTROL_LOOP_FREQUENCY_HZ"
#elif (CONTROL_LOOP_FREQUENCY_HZ % POSITION_LOOP_FREQUENCY_HZ) != 0U
#error "POSITION_LOOP_FREQUENCY_HZ must divide CONTROL_LOOP_FREQUENCY_HZ exactly"
#endif
#define POSITION_LOOP_DIVIDER       (CONTROL_LOOP_FREQUENCY_HZ / POSITION_LOOP_FREQUENCY_HZ)
#define POSITION_LOOP_PERIOD_S      (1.0f / (float)POSITION_LOOP_FREQUENCY_HZ)

/* Cascaded position-speed-current controller runs at 5 kHz. */
#define CASCADE_POSITION_LOOP_FREQUENCY_HZ  5000U
#if CASCADE_POSITION_LOOP_FREQUENCY_HZ == 0U
#error "CASCADE_POSITION_LOOP_FREQUENCY_HZ must be greater than zero"
#elif CASCADE_POSITION_LOOP_FREQUENCY_HZ > CONTROL_LOOP_FREQUENCY_HZ
#error "CASCADE_POSITION_LOOP_FREQUENCY_HZ must not exceed CONTROL_LOOP_FREQUENCY_HZ"
#elif (CONTROL_LOOP_FREQUENCY_HZ % CASCADE_POSITION_LOOP_FREQUENCY_HZ) != 0U
#error "CASCADE_POSITION_LOOP_FREQUENCY_HZ must divide CONTROL_LOOP_FREQUENCY_HZ exactly"
#endif
#define CASCADE_POSITION_LOOP_DIVIDER (CONTROL_LOOP_FREQUENCY_HZ / CASCADE_POSITION_LOOP_FREQUENCY_HZ)
#define CASCADE_POSITION_LOOP_PERIOD_S (1.0f / (float)CASCADE_POSITION_LOOP_FREQUENCY_HZ)

#endif
