#ifndef PRODUCT_MOTOR_SAFETY_LIMITS_H
#define PRODUCT_MOTOR_SAFETY_LIMITS_H

#define MOTOR_LIMIT_CASCADE_POSITION_KP_PER_S       50.0f
#define MOTOR_LIMIT_CASCADE_POSITION_KD             10.0f
#define MOTOR_LIMIT_POSITION_KP_A_PER_RAD            50.0f
#define MOTOR_LIMIT_POSITION_KD_A_PER_RAD_S          10.0f
#define MOTOR_LIMIT_POSITION_KI_A_PER_RAD_S          10.0f
#define MOTOR_LIMIT_POSITION_SPEED_RPS                0.125f

#endif
