#ifndef CORE_INFRASTRUCTURE_PARAMETERS_PARAMETER_SCHEMA_H
#define CORE_INFRASTRUCTURE_PARAMETERS_PARAMETER_SCHEMA_H

#include "Core/Config/product_manifest.h"

#define PARAM_SCHEMA_VERSION PRODUCT_PARAMETER_SCHEMA_VERSION
#define PARAM_SCHEMA_VERSION_PREVIOUS_COGGING         9U
#define PARAM_SCHEMA_VERSION_PREVIOUS_FRICTION          8U
#define PARAM_SCHEMA_VERSION_PREVIOUS_INTEGRAL_LIMIT    7U
#define PARAM_SCHEMA_VERSION_PREVIOUS_CURRENT_SENSE     6U
#define PARAM_SCHEMA_PREVIOUS_CASCADE_SHUNT_MILLIOHM    2U
#define PARAM_SCHEMA_PREVIOUS_IMPEDANCE_SHUNT_MILLIOHM  6U
#define PARAM_SCHEMA_VERSION_PREVIOUS_IMPEDANCE         5U
#define PARAM_SCHEMA_VERSION_PREVIOUS_CASCADE           4U

#endif
