#ifndef __CURRENT_SENSE_PROFILE_H__
#define __CURRENT_SENSE_PROFILE_H__

/*
 * Change only CURRENT_SENSE_SHUNT_MILLIOHM to switch the complete current-
 * sensing configuration. It may also be overridden from the compiler command
 * line. All current values below are phase-current amplitudes in amperes.
 */
#define CURRENT_SENSE_SHUNT_2_MILLIOHM             2U
#define CURRENT_SENSE_SHUNT_6_MILLIOHM             6U

#ifndef CURRENT_SENSE_SHUNT_MILLIOHM
#define CURRENT_SENSE_SHUNT_MILLIOHM               CURRENT_SENSE_SHUNT_6_MILLIOHM
#endif

#define CURRENT_SENSE_PROFILE_AMPLIFIER_GAIN       10.0f

#if CURRENT_SENSE_SHUNT_MILLIOHM == CURRENT_SENSE_SHUNT_2_MILLIOHM

#define CURRENT_SENSE_PROFILE_SHUNT_RESISTANCE_OHM 0.002f
#define CURRENT_SENSE_PROFILE_RELIABLE_LIMIT_A      60.0f
#define CURRENT_SENSE_PROFILE_COMMAND_LIMIT_MAX_A   30.0f
#define CURRENT_SENSE_PROFILE_CALIB_LIMIT_MAX_A     30.0f
#define CURRENT_SENSE_PROFILE_OVERCURRENT_TRIP_A    40.0f
#define CURRENT_SENSE_PROFILE_DEFAULT_CALIB_A       10.0f
#define CURRENT_SENSE_PROFILE_DEFAULT_LIMIT_A       30.0f
#define CURRENT_SENSE_PROFILE_PATH_COMPENSATION_OHM 0.004f

#elif CURRENT_SENSE_SHUNT_MILLIOHM == CURRENT_SENSE_SHUNT_6_MILLIOHM

#define CURRENT_SENSE_PROFILE_SHUNT_RESISTANCE_OHM 0.006f
#define CURRENT_SENSE_PROFILE_RELIABLE_LIMIT_A      20.0f
#define CURRENT_SENSE_PROFILE_COMMAND_LIMIT_MAX_A   10.0f
#define CURRENT_SENSE_PROFILE_CALIB_LIMIT_MAX_A     10.0f
#define CURRENT_SENSE_PROFILE_OVERCURRENT_TRIP_A    18.0f
#define CURRENT_SENSE_PROFILE_DEFAULT_CALIB_A       3.0f
#define CURRENT_SENSE_PROFILE_DEFAULT_LIMIT_A       6.0f
#define CURRENT_SENSE_PROFILE_PATH_COMPENSATION_OHM 0.008f

#else
#error "Unsupported CURRENT_SENSE_SHUNT_MILLIOHM; select 2U or 6U"
#endif

#endif
