#ifndef __HW_CONF_H__
#define __HW_CONF_H__

#include "main.h"
#include "control_config.h"
#include "motor_hardware_profile.h"
#include "motor_sensing.h"
#include "current_sense_profile.h"

#define PWM_TIM_CLOCK 170000000
/* 板级 PWM 定时器实现 control_config.h 的电流环频率契约。 */
#define PWM_TIM_FREQ FOC_FREQ
#define PWM_TIM_PERIOD (PWM_TIM_CLOCK / PWM_TIM_FREQ / 2)
#define PWM_PERIOD 5e-5f

/* RTT 输出采样频率，必须整除 FOC_FREQ。 */
#define RTT_SAMPLE_RATE_HZ 2000U

#if RTT_SAMPLE_RATE_HZ == 0U
#error "RTT_SAMPLE_RATE_HZ must be greater than zero"
#elif RTT_SAMPLE_RATE_HZ > FOC_FREQ
#error "RTT_SAMPLE_RATE_HZ must not exceed FOC_FREQ"
#elif (FOC_FREQ % RTT_SAMPLE_RATE_HZ) != 0U
#error "RTT_SAMPLE_RATE_HZ must divide FOC_FREQ exactly"
#endif

#define RTT_SAMPLE_DIVIDER (FOC_FREQ / RTT_SAMPLE_RATE_HZ)

/* 固定 4 通道 int16 帧：位置/转速/Iq 指令/Iq 反馈，布局见 rtt_telemetry.c。 */
#define RTT_JSCOPE_DESCRIPTOR "JScope_i2i2i2i2"

/* Three-phase low-side current sensing; selected in current_sense_profile.h. */
#define SENSING_RES CURRENT_SENSE_PROFILE_SHUNT_RESISTANCE_OHM
#define CURRENT_AMP_GAIN CURRENT_SENSE_PROFILE_AMPLIFIER_GAIN
/* 换算常量归 platform/api/motor_sensing.h 所有；此处保留历史名称。 */
#define SENSING_CURR_FACTOR MOTOR_SENSING_CURRENT_A_PER_COUNT
#define ADC2_SUM_TO_COUNTS MOTOR_SENSING_ADC_SUM_TO_COUNTS

/* Keep normal control and software protection below the amplifier/ADC rails. */
#define CURRENT_SENSE_RELIABLE_LIMIT_A CURRENT_SENSE_PROFILE_RELIABLE_LIMIT_A
#define CURRENT_COMMAND_LIMIT_MAX_A CURRENT_SENSE_PROFILE_COMMAND_LIMIT_MAX_A
#define CURRENT_CALIB_LIMIT_MAX_A CURRENT_SENSE_PROFILE_CALIB_LIMIT_MAX_A
#define CURRENT_OVERCURRENT_TRIP_A MOTOR_SENSING_OVERCURRENT_TRIP_A

/*bus voltagge R1 R2 (kohm)*/
#define VBUS_R1 MOTOR_SENSING_VBUS_R1_KOHM
#define VBUS_R2 MOTOR_SENSING_VBUS_R2_KOHM
/*bus voltage sensing factor (adc value/V)*/
#define SENSING_VBUS_FACTOR MOTOR_SENSING_VBUS_V_PER_COUNT

#define TEMP_R2 3.3f

/*MOSFET approximate deadtime (s)*/
#define MOS_DEADTIME 2.1e-7f
/*voltage of body diode (V)*/
#define MOS_VDIODE 0.5f

#define DBC_FACTOR MOS_DEADTIME / PWM_PERIOD / 1000000000.0f

#define CURRENT_ADC ADC2
#define IA_ADC_CHANNEL JDR1
#define IB_ADC_CHANNEL JDR2
#define IC_ADC_CHANNEL JDR3

#define VBUS_ADC ADC2
#define VBUS_ADC_CHANNEL JDR4

#define TEMP_ADC ADC1
#define TEMP_ADC_CHANNEL JDR1

#if MOTOR_HAS_DAMPING_RING == MOTOR_DAMPING_RING_ENABLED
#define SENSORLESS_ENCODER_CALIB_ALIGN_CURRENT_RAMP_TIME_S 0.80f
#define SENSORLESS_ENCODER_CALIB_ALIGN_HOLD_TIME_S 0.50f
#define SENSORLESS_ENCODER_CALIB_ALIGN_CURRENT_A 3.5f
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_INITIAL_A 3.5f
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_A 4.5f
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_RAMP_TIME_S 1.00f
#define SENSORLESS_ENCODER_CALIB_STARTUP_ID_A 0.5f
#define SENSORLESS_ENCODER_CALIB_MIN_CURRENT_LIMIT_A 5.5f
#define SENSORLESS_ENCODER_CALIB_MIN_ELEC_VEL_RAD_S 250.0f
#define SENSORLESS_ENCODER_CALIB_TARGET_ELEC_VEL_RAD_S 420.0f
#define SENSORLESS_ENCODER_CALIB_SPEED_MEC_RAD_S 20.0f
#define SENSORLESS_ENCODER_CALIB_STARTUP_RAMP_TIME_S 2.00f
#define SENSORLESS_ENCODER_CALIB_SPEED_LOCK_TIME_S 0.20f
#define SENSORLESS_ENCODER_CALIB_SPEED_LOCK_FILTER_ALPHA 0.01f
#define SENSORLESS_ENCODER_CALIB_OBSERVER_LOCK_RATIO 0.25f
#define SENSORLESS_ENCODER_CALIB_ANGLE_HANDOFF_TIME_S 0.10f
#define SENSORLESS_ENCODER_CALIB_LOCK_TIMEOUT_S 5.00f
#define SENSORLESS_ENCODER_CALIB_ID_RAMP_DOWN_TIME_S 0.50f
#define SENSORLESS_ENCODER_CALIB_OBSERVER_LOSS_TIME_S 0.20f
#define SENSORLESS_ENCODER_CALIB_SPEED_STABLE_TIMEOUT_S 10.00f
#define SENSORLESS_ENCODER_CALIB_MECH_TURNS 5U
#define SENSORLESS_ENCODER_CALIB_STARTUP_TIMEOUT_S 12.0f
#define SENSORLESS_ENCODER_CALIB_STOP_CURRENT_RAMP_TIME_S 0.10f
#define ENCODER_ELEC_ZERO_MIN_ALIGN_CURRENT_A 4.5f
#elif MOTOR_HAS_DAMPING_RING == MOTOR_DAMPING_RING_DISABLED
#define SENSORLESS_ENCODER_CALIB_ALIGN_CURRENT_RAMP_TIME_S SENSORLESS_ALIGN_CURRENT_RAMP_TIME_S
#define SENSORLESS_ENCODER_CALIB_ALIGN_HOLD_TIME_S SENSORLESS_ALIGN_HOLD_TIME_S
#define SENSORLESS_ENCODER_CALIB_ALIGN_CURRENT_A SENSORLESS_ALIGN_CURRENT_A
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_INITIAL_A SENSORLESS_STARTUP_IQ_INITIAL_A
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_A SENSORLESS_STARTUP_IQ_A
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_RAMP_TIME_S SENSORLESS_STARTUP_IQ_RAMP_TIME_S
#define SENSORLESS_ENCODER_CALIB_STARTUP_ID_A SENSORLESS_STARTUP_ID_A
#define SENSORLESS_ENCODER_CALIB_MIN_CURRENT_LIMIT_A 0.0f
#define SENSORLESS_ENCODER_CALIB_MIN_ELEC_VEL_RAD_S SENSORLESS_STARTUP_MIN_ELEC_VEL_RAD_S
/* 21-pole-pair, unloaded motor: steady calibration target is about 143 rpm.
 * Handoff transients and normal wheel speed limits are separate. */
#define SENSORLESS_ENCODER_CALIB_TARGET_ELEC_VEL_RAD_S 315.0f
#define SENSORLESS_ENCODER_CALIB_SPEED_MEC_RAD_S 15.0f
#define SENSORLESS_ENCODER_CALIB_STARTUP_RAMP_TIME_S SENSORLESS_STARTUP_RAMP_TIME_S
#define SENSORLESS_ENCODER_CALIB_SPEED_LOCK_TIME_S SENSORLESS_STARTUP_SPEED_LOCK_TIME_S
#define SENSORLESS_ENCODER_CALIB_SPEED_LOCK_FILTER_ALPHA SENSORLESS_SPEED_LOCK_FILTER_ALPHA
#define SENSORLESS_ENCODER_CALIB_OBSERVER_LOCK_RATIO SENSORLESS_OBSERVER_LOCK_RATIO
#define SENSORLESS_ENCODER_CALIB_ANGLE_HANDOFF_TIME_S SENSORLESS_ANGLE_HANDOFF_TIME_S
#define SENSORLESS_ENCODER_CALIB_LOCK_TIMEOUT_S SENSORLESS_STARTUP_LOCK_TIMEOUT_S
#define SENSORLESS_ENCODER_CALIB_ID_RAMP_DOWN_TIME_S SENSORLESS_ID_RAMP_DOWN_TIME_S
#define SENSORLESS_ENCODER_CALIB_OBSERVER_LOSS_TIME_S SENSORLESS_OBSERVER_LOSS_TIME_S
#define SENSORLESS_ENCODER_CALIB_SPEED_STABLE_TIMEOUT_S 5.00f
#define SENSORLESS_ENCODER_CALIB_MECH_TURNS 10U
#define SENSORLESS_ENCODER_CALIB_STARTUP_TIMEOUT_S 8.0f
#define SENSORLESS_ENCODER_CALIB_STOP_CURRENT_RAMP_TIME_S 0.50f
#define ENCODER_ELEC_ZERO_MIN_ALIGN_CURRENT_A 0.0f
#else
#error "MOTOR_HAS_DAMPING_RING must be MOTOR_DAMPING_RING_ENABLED or MOTOR_DAMPING_RING_DISABLED"
#endif

#define SENSORLESS_ENCODER_CALIB_SPEED_ERROR_RATIO 0.20f
#define SENSORLESS_ENCODER_CALIB_SPEED_STABLE_TIME_S 0.50f
#define SENSORLESS_ENCODER_CALIB_ALIGN_SAMPLE_TIME_S 0.10f
#define SENSORLESS_ENCODER_CALIB_VERIFY_MECH_TURNS 1U
#define SENSORLESS_ENCODER_CALIB_MIN_SAMPLES_PER_BIN 16U
#define SENSORLESS_ENCODER_CALIB_LUT_BUILD_BINS_PER_CYCLE 8U
#define SENSORLESS_ENCODER_CALIB_FIND_ORIGIN_TIMEOUT_S 1.50f
#define SENSORLESS_ENCODER_CALIB_SAMPLE_TIMEOUT_S 12.00f
#define SENSORLESS_ENCODER_CALIB_VERIFY_TIMEOUT_S 4.00f
#define SENSORLESS_ENCODER_CALIB_MAX_RMS_RESIDUAL_Q15 256U
#define SENSORLESS_ENCODER_CALIB_MAX_PEAK_RESIDUAL_Q15 1024U
#define SENSORLESS_ENCODER_CALIB_STOP_SPEED_MARGIN 1.05f
#define SENSORLESS_ENCODER_CALIB_STOP_DECEL_TIME_S 1.00f
#define SENSORLESS_ENCODER_CALIB_STOP_DECEL_TIMEOUT_S 3.00f
#define SENSORLESS_ENCODER_CALIB_STOP_SPEED_TOLERANCE_RATIO 0.10f

/* Encoder electrical-zero alignment. */
#define ENCODER_ELEC_ZERO_CURRENT_RAMP_TIME_S 0.50f
#define ENCODER_ELEC_ZERO_HOLD_TIME_S 1.00f

#endif
