"""Generate the Loader Keil project from the APP project.

Creates:
  MDK-ARM/Vector_Mini_ST_Loader/Vector_Mini_ST_Loader.sct
  MDK-ARM/Vector_Mini_ST_Loader.uvprojx
The loader target links at 0x08000000 (12 KiB, pages 0-5). The remaining
3.5 pages inside the 16 KiB loader partition are: page 6 app record
(0x08003000) and page 7 spare (0x08003800).
"""
from pathlib import Path
import os
import xml.etree.ElementTree as ET

REPO = Path(__file__).resolve().parents[3]
SRC = REPO / "firmware/platform/stm32g4/cubemx/MDK-ARM/Vector_Mini_ST.uvprojx"
DST = REPO / "loader" / "mdk" / "Vector_Mini_ST_Loader.uvprojx"
SCT_DIR = REPO / "loader" / "mdk" / "Vector_Mini_ST_Loader"
SCT = SCT_DIR / "Vector_Mini_ST_Loader.sct"

TARGET_NAME = "Vector_Mini_ST_Loader"

HAL_WHITELIST = [
    "stm32g4xx_hal.c",
    "stm32g4xx_hal_cortex.c",
    "stm32g4xx_hal_rcc.c",
    "stm32g4xx_hal_rcc_ex.c",
    "stm32g4xx_hal_gpio.c",
    "stm32g4xx_hal_fdcan.c",
    "stm32g4xx_hal_flash.c",
    "stm32g4xx_hal_flash_ex.c",
    "stm32g4xx_hal_pwr.c",
    "stm32g4xx_hal_pwr_ex.c",
]

LOADER_FILES = [
    "loader_main.c",
    "loader_can.c",
    "loader_flash.c",
    "loader_crc.c",
    "loader_proto.c",
    "loader_jump.c",
]

SCATTER_TEXT = """; *************************************************************
; *** Scatter-Loading Description File generated by uVision ***
; *************************************************************

LR_IROM1 0x08000000 0x00003000  {    ; Loader load region (pages 0-5)
  ER_IROM1 0x08000000 0x00003000  {  ; load address = execution address
   *.o (RESET, +First)
   *(InRoot$$Sections)
   .ANY (+RO)
   .ANY (+XO)
  }
  RW_IRAM1 0x20000020 0x00007FE0  {  ; RW data (first 32 bytes reserved for boot mailbox)
   .ANY (+RW +ZI)
  }
}
"""


def make_file(name: str, ftype: str, path: str) -> ET.Element:
    el = ET.Element("File")
    ET.SubElement(el, "FileName").text = name
    ET.SubElement(el, "FileType").text = ftype
    ET.SubElement(el, "FilePath").text = path
    return el


def collect_clones(root: ET.Element) -> dict[str, ET.Element]:
    out: dict[str, ET.Element] = {}
    for file_el in root.iter("File"):
        name_el = file_el.find("FileName")
        if name_el is not None and name_el.text and name_el.text not in out:
            out[name_el.text] = file_el
    return out


def main() -> int:
    assert SRC.exists(), f"missing {SRC}"
    text = SRC.read_text(encoding="utf-8")
    root = ET.fromstring(text)
    clones = collect_clones(root)

    target = root.find("Targets/Target")
    assert target is not None

    target.find("TargetName").text = TARGET_NAME

    common = root.find("Targets/Target/TargetOption/TargetCommonOption")
    assert common is not None
    out_dir = common.find("OutputDirectory")
    if out_dir is not None:
        out_dir.text = "../../outputs/build/keil/Vector_Mini_ST_Loader/"
    out_name = common.find("OutputName")
    if out_name is not None:
        out_name.text = TARGET_NAME

    cpu = common.find("Cpu")
    if cpu is not None:
        cpu.text = ('IRAM(0x20000020-0x20007FFF) IROM(0x8000000-0x8002FFF)  '
                    'CLOCK(8000000) FPU2 CPUTYPE("Cortex-M4") TZ')

    for tag, start, size in (("IROM", "0x8000000", "0x3000"), ("IRAM", "0x20000020", "0x7FE0")):
        for elem in root.iter(tag):
            sa = elem.find("StartAddress")
            sz = elem.find("Size")
            if sa is not None:
                sa.text = start
            if sz is not None:
                sz.text = size

    ldads = root.find("Targets/Target/TargetOption/TargetArmAds/LDads")
    if ldads is not None:
        umf = ldads.find("umfTarg")
        if umf is not None:
            umf.text = "0"
        sc = ldads.find("ScatterFile")
        if sc is not None:
            sc.text = "Vector_Mini_ST_Loader\\Vector_Mini_ST_Loader.sct"

    vc = root.find("Targets/Target/TargetOption/TargetArmAds/Cads/VariousControls")
    assert vc is not None
    define = vc.find("Define")
    if define is not None:
        define.text = "USE_HAL_DRIVER,STM32G431xx"
    inc = vc.find("IncludePath")
    if inc is not None:
        parts = [p.strip() for p in (inc.text or "").split(";") if p.strip()]
        rebased = [os.path.relpath((SRC.parent / p.replace("\\", "/")).resolve(), DST.parent)
                   for p in parts]
        inc.text = ";".join(rebased)

    listing = common.find("ListingPath")
    if listing is not None:
        listing.text = "../../outputs/build/keil/Vector_Mini_ST_Loader/"
    after = common.find("AfterMake/UserProg1Name")
    if after is not None:
        after.text = ('python "../../host_app/tools/check_app_layout.py" --target loader '
                      '--map "../../outputs/build/keil/Vector_Mini_ST_Loader/Vector_Mini_ST_Loader.map"')

    groups_el = target.find("Groups")
    assert groups_el is not None
    for g in list(groups_el):
        groups_el.remove(g)

    def add_group(name: str, files: list[ET.Element]) -> None:
        g = ET.SubElement(groups_el, "Group")
        ET.SubElement(g, "GroupName").text = name
        files_el = ET.SubElement(g, "Files")
        for f in files:
            files_el.append(f)

    # Loader sources
    ldr_files = []
    for name in LOADER_FILES:
        ldr_files.append(make_file(name, "1", f"..\\firmware\\{name}"))
    add_group("Loader", ldr_files)

    # Startup + system
    startup = clones.get("startup_stm32g431xx.s")
    if startup is None:
        startup = make_file("startup_stm32g431xx.s", "2", r"..\..\firmware\platform\stm32g4\cubemx\MDK-ARM\startup_stm32g431xx.s")
    else:
        startup.find("FilePath").text = r"..\..\firmware\platform\stm32g4\cubemx\MDK-ARM\startup_stm32g431xx.s"
    add_group("Startup", [startup])

    system = clones.get("system_stm32g4xx.c")
    if system is None:
        system = make_file("system_stm32g4xx.c", "1", "..\\Core\\Src\\system_stm32g4xx.c")
    add_group("Core", [system])

    # HAL whitelist
    hal_files = []
    missing = []
    for name in HAL_WHITELIST:
        f = clones.get(name)
        if f is None:
            missing.append(name)
            f = make_file(name, "1", f"..\\Drivers\\STM32G4xx_HAL_Driver\\Src\\{name}")
        hal_files.append(f)
    add_group("HAL", hal_files)

    # 按实际源目录迁移公共 MCU 文件，不依赖旧工程目录层级。
    for f in root.iter("File"):
        name = f.findtext("FileName")
        if name == "startup_stm32g431xx.s":
            source = SRC.parent / name
        elif name == "system_stm32g4xx.c":
            source = SRC.parent.parent / "Core/Src" / name
        elif name in HAL_WHITELIST:
            source = SRC.parent.parent / "Drivers/STM32G4xx_HAL_Driver/Src" / name
        else:
            continue
        f.find("FilePath").text = os.path.relpath(source, DST.parent)

    SCT_DIR.mkdir(parents=True, exist_ok=True)
    SCT.write_text(SCATTER_TEXT, encoding="ascii")

    tree = ET.ElementTree(root)
    tree.write(DST, encoding="utf-8", xml_declaration=True)

    print(f"wrote {DST}")
    print(f"wrote {SCT}")
    if missing:
        print(f"WARNING: not found in APP project, constructed manually: {missing}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
