"""Patch the APP Keil projects for the resident-loader layout.

Edits (both MDK-ARM/Vector_Mini_ST.uvprojx and Vector_Mini_ST_HIL.uvprojx):
  IROM 0x08000000/0x1C000 -> 0x08004000/0x18000
  IRAM 0x20000000/0x8000  -> 0x20000020/0x7FE0
  CPU string IROM/IRAM ranges updated accordingly
  Defines += APP_VTOR_OFFSET=0x4000 (relocated vector table)
  IncludePath += ..\\shared (boot_mailbox.h)
Idempotent: skips values that are already patched.
"""
from pathlib import Path
import xml.etree.ElementTree as ET

REPO = Path(__file__).resolve().parents[3]
PROJECTS = [
    REPO / "MDK-ARM" / "Vector_Mini_ST.uvprojx",
    REPO / "MDK-ARM" / "Vector_Mini_ST_HIL.uvprojx",
]
APP_SCT = REPO / "MDK-ARM" / "Vector_Mini_ST" / "Vector_Mini_ST.sct"

APP_SCATTER_TEXT = """; *************************************************************
; *** Scatter-Loading Description File generated by uVision ***
; *************************************************************

LR_IROM1 0x08004000 0x00018000  {    ; APP load region (pages 8-55)
  ER_IROM1 0x08004000 0x00018000  {  ; load address = execution address
   *.o (RESET, +First)
   *(InRoot$$Sections)
   .ANY (+RO)
   .ANY (+XO)
  }
  RW_IRAM1 0x20000020 0x00007FE0  {  ; RW data (first 32 bytes reserved for boot mailbox)
   .ANY (+RW +ZI)
  }
}
"""


def patch(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    root = ET.fromstring(text)
    changes: list[str] = []

    common = root.find("Targets/Target/TargetOption/TargetCommonOption")
    assert common is not None, f"{path.name}: TargetCommonOption missing"

    cpu = common.find("Cpu")
    if cpu is not None and cpu.text:
        new = cpu.text.replace("IROM(0x8000000-0x801BFFF)", "IROM(0x8004000-0x801BFFF)")
        new = new.replace("IRAM(0x20000000-0x20007FFF)", "IRAM(0x20000020-0x20007FFF)")
        if new != cpu.text:
            changes.append(f"cpu: {cpu.text!r} -> {new!r}")
            cpu.text = new

    for tag, start, size in (("IROM", "0x8004000", "0x18000"), ("IRAM", "0x20000020", "0x7FE0")):
        for elem in root.iter(tag):
            sa = elem.find("StartAddress")
            sz = elem.find("Size")
            if sa is not None and sa.text and sa.text.lower() != start.lower():
                changes.append(f"{tag} start {sa.text} -> {start}")
                sa.text = start
            if sz is not None and sz.text and sz.text.lower() != size.lower():
                changes.append(f"{tag} size {sz.text} -> {size}")
                sz.text = size

    # Ensure IRAM start patched even if value was something else (safety).
    for elem in root.iter("IRAM"):
        sa = elem.find("StartAddress")
        if sa is not None:
            sa.text = "0x20000020"

    vc = root.find("Targets/Target/TargetOption/TargetArmAds/Cads/VariousControls")
    assert vc is not None, f"{path.name}: VariousControls missing"

    define = vc.find("Define")
    if define is not None:
        cur = (define.text or "").strip()
        if "APP_VTOR_OFFSET" not in cur:
            parts = [p for p in cur.split(",") if p]
            parts.append("APP_VTOR_OFFSET=0x4000")
            define.text = ",".join(parts)
            changes.append(f"Define -> {define.text}")

    inc = vc.find("IncludePath")
    if inc is not None:
        cur = (inc.text or "").strip()
        if "..\\shared" not in cur and "../shared" not in cur:
            inc.text = (cur + ";..\\shared") if cur else "..\\shared"
            changes.append("IncludePath += ..\\shared")

    ldads = root.find("Targets/Target/TargetOption/TargetArmAds/LDads")
    if ldads is not None:
        umf = ldads.find("umfTarg")
        if umf is not None and umf.text != "0":
            umf.text = "0"
            changes.append("umfTarg -> 0 (use custom scatter)")
        sc = ldads.find("ScatterFile")
        if sc is not None and sc.text != "Vector_Mini_ST\\Vector_Mini_ST.sct":
            sc.text = "Vector_Mini_ST\\Vector_Mini_ST.sct"
            changes.append("ScatterFile -> Vector_Mini_ST\\Vector_Mini_ST.sct")

    if changes:
        tree = ET.ElementTree(root)
        tree.write(path, encoding="utf-8", xml_declaration=True)
        changes.insert(0, "written")
    return changes


def main() -> int:
    APP_SCT.parent.mkdir(parents=True, exist_ok=True)
    APP_SCT.write_text(APP_SCATTER_TEXT, encoding="ascii")
    print(f"wrote {APP_SCT}")
    for p in PROJECTS:
        if not p.exists():
            print(f"SKIP missing {p}")
            continue
        ch = patch(p)
        print(f"=== {p.name} ===")
        for c in ch:
            print("   ", c)
        if not ch:
            print("    (already patched)")


if __name__ == "__main__":
    raise SystemExit(main())
