#ifndef FIRMWARE_BSP_BOARDS_VECTOR_MINI_ST_VECTOR_MINI_ST_BSP_H
#define FIRMWARE_BSP_BOARDS_VECTOR_MINI_ST_VECTOR_MINI_ST_BSP_H

#include "../bsp_board.h"

#ifdef __cplusplus
extern "C" {
#endif

#define BSP_VECTOR_MINI_ST_BOARD_ID            0x564D0001UL
#define BSP_VECTOR_MINI_ST_BINDING_FINGERPRINT 0x564D53A1UL

enum
{
	BSP_VECTOR_MINI_ST_MOTOR_DRIVE_ENDPOINT_MAIN = 0x0100U,
	BSP_VECTOR_MINI_ST_CURRENT_SENSOR_ENDPOINT_PHASE_A = 0x0101U,
	BSP_VECTOR_MINI_ST_CURRENT_SENSOR_ENDPOINT_PHASE_B = 0x0102U,
	BSP_VECTOR_MINI_ST_CURRENT_SENSOR_ENDPOINT_PHASE_C = 0x0103U
};

enum
{
	BSP_VECTOR_MINI_ST_ANGLE_ENDPOINT_ONBOARD = 0x0201U,
	BSP_VECTOR_MINI_ST_ANGLE_ENDPOINT_EXTERNAL = 0x0202U
};

enum
{
	BSP_VECTOR_MINI_ST_TEMPERATURE_ENDPOINT_PROCESSOR = 0x0301U,
	BSP_VECTOR_MINI_ST_TEMPERATURE_ENDPOINT_POWER_STAGE_OPTION = 0x0302U
};

enum
{
	BSP_VECTOR_MINI_ST_COMMUNICATION_ENDPOINT_FIELD_BUS = 0x0401U,
	BSP_VECTOR_MINI_ST_COMMUNICATION_ENDPOINT_SERVICE_STREAM = 0x0402U
};

extern const BspBoardCapabilities BspVectorMiniSt_Capabilities;
extern const BspBoardRuntimeIdentity BspVectorMiniSt_RuntimeIdentity;

BspBoardValidationResult BspVectorMiniSt_ValidateBindingRequest(
	const BspBoardBindingRequest *request);

#ifdef __cplusplus
}
#endif

#endif
