#ifndef FIRMWARE_BSP_BOARDS_VECTOR_MINI_ST_MEMORY_MAP_H
#define FIRMWARE_BSP_BOARDS_VECTOR_MINI_ST_MEMORY_MAP_H

/* Physical Flash ownership belongs to the selected board package. Keep the
 * linker application region and the reserved parameter region adjacent. */
#define BSP_VECTOR_MINI_ST_FLASH_BASE_ADDRESS              0x08000000UL
#define BSP_VECTOR_MINI_ST_FLASH_CAPACITY_BYTES             0x00020000UL
#define BSP_VECTOR_MINI_ST_APPLICATION_CAPACITY_BYTES       0x0001C000UL
#define BSP_VECTOR_MINI_ST_PARAMETER_STORAGE_BASE_ADDRESS   0x0801C000UL
#define BSP_VECTOR_MINI_ST_PARAMETER_STORAGE_CAPACITY_BYTES 16384U
#define BSP_VECTOR_MINI_ST_FLASH_ERASE_SIZE_BYTES           2048U
#define BSP_VECTOR_MINI_ST_FLASH_PROGRAM_ALIGNMENT_BYTES    8U

#if BSP_VECTOR_MINI_ST_PARAMETER_STORAGE_BASE_ADDRESS != \
	(BSP_VECTOR_MINI_ST_FLASH_BASE_ADDRESS + \
	 BSP_VECTOR_MINI_ST_APPLICATION_CAPACITY_BYTES)
#error "VectorMiniSt parameter storage must follow the application region"
#endif

#if (BSP_VECTOR_MINI_ST_APPLICATION_CAPACITY_BYTES + \
	 BSP_VECTOR_MINI_ST_PARAMETER_STORAGE_CAPACITY_BYTES) != \
	BSP_VECTOR_MINI_ST_FLASH_CAPACITY_BYTES
#error "VectorMiniSt Flash regions must cover the physical Flash exactly"
#endif

#endif
