#include "vector_mini_st_bsp.h"
#include "vector_mini_st_memory_map.h"

#define ARRAY_COUNT(array_) (sizeof(array_) / sizeof((array_)[0]))

static const BspMotorDriveEndpointCapabilities MotorDriveEndpoints[] =
{
	{
		BSP_VECTOR_MINI_ST_MOTOR_DRIVE_ENDPOINT_MAIN,
		BSP_ENDPOINT_AVAILABLE,
		BSP_CURRENT_SENSE_TOPOLOGY_BIT(
			BSP_CURRENT_SENSE_LOW_SIDE_THREE_SHUNT),
		3U,
		{
			BSP_VECTOR_MINI_ST_CURRENT_SENSOR_ENDPOINT_PHASE_A,
			BSP_VECTOR_MINI_ST_CURRENT_SENSOR_ENDPOINT_PHASE_B,
			BSP_VECTOR_MINI_ST_CURRENT_SENSOR_ENDPOINT_PHASE_C
		},
		true,
		false,
		BSP_CURRENT_SAMPLING_MODE_BIT(BSP_CURRENT_SAMPLING_MODE_FIXED)
	}
};

static const BspAngleSensorEndpointCapabilities AngleSensorEndpoints[] =
{
	{
		BSP_VECTOR_MINI_ST_ANGLE_ENDPOINT_ONBOARD,
		BSP_ENDPOINT_AVAILABLE,
		BSP_ANGLE_ENDPOINT_SYNCHRONOUS_SERIAL,
		16U,
		true,
		true,
		false
	},
	{
		BSP_VECTOR_MINI_ST_ANGLE_ENDPOINT_EXTERNAL,
		BSP_ENDPOINT_AVAILABLE,
		BSP_ANGLE_ENDPOINT_SYNCHRONOUS_SERIAL,
		16U,
		true,
		true,
		false
	}
};

static const BspTemperatureEndpointCapabilities TemperatureEndpoints[] =
{
	{
		BSP_VECTOR_MINI_ST_TEMPERATURE_ENDPOINT_PROCESSOR,
		BSP_ENDPOINT_AVAILABLE,
		BSP_TEMPERATURE_SOURCE_PROCESSOR_DIE,
		BSP_TEMPERATURE_LOCATION_PROCESSOR,
		false,
		false
	},
	{
		BSP_VECTOR_MINI_ST_TEMPERATURE_ENDPOINT_POWER_STAGE_OPTION,
		BSP_ENDPOINT_PROVISIONED_UNPOPULATED,
		BSP_TEMPERATURE_SOURCE_ANALOG_RESISTIVE,
		BSP_TEMPERATURE_LOCATION_POWER_STAGE,
		true,
		true
	}
};

static const BspCommunicationEndpointCapabilities CommunicationEndpoints[] =
{
	{
		BSP_VECTOR_MINI_ST_COMMUNICATION_ENDPOINT_FIELD_BUS,
		BSP_ENDPOINT_AVAILABLE,
		BSP_COMMUNICATION_CAN,
		BSP_COMMUNICATION_FEATURE_CAN_CLASSIC |
			BSP_COMMUNICATION_FEATURE_CAN_FD |
			BSP_COMMUNICATION_FEATURE_CAN_BRS,
		8U,
		1000000U,
		5000000U
	},
	{
		BSP_VECTOR_MINI_ST_COMMUNICATION_ENDPOINT_SERVICE_STREAM,
		BSP_ENDPOINT_AVAILABLE,
		BSP_COMMUNICATION_BYTE_STREAM,
		BSP_COMMUNICATION_FEATURE_BYTE_STREAM |
			BSP_COMMUNICATION_FEATURE_FULL_DUPLEX,
		64U,
		0U,
		0U
	}
};

const BspBoardCapabilities BspVectorMiniSt_Capabilities =
{
	"VectorMiniSt",
	BSP_VECTOR_MINI_ST_BOARD_ID,
	BSP_VECTOR_MINI_ST_BINDING_FINGERPRINT,
	MotorDriveEndpoints,
	ARRAY_COUNT(MotorDriveEndpoints),
	AngleSensorEndpoints,
	ARRAY_COUNT(AngleSensorEndpoints),
	TemperatureEndpoints,
	ARRAY_COUNT(TemperatureEndpoints),
	CommunicationEndpoints,
	ARRAY_COUNT(CommunicationEndpoints),
	{
		BSP_SYSTEM_FEATURE_MONOTONIC_CLOCK |
			BSP_SYSTEM_FEATURE_EXECUTION_TIMER |
			BSP_SYSTEM_FEATURE_CRITICAL_SECTION |
			BSP_SYSTEM_FEATURE_UNIQUE_ID |
			BSP_SYSTEM_FEATURE_NONVOLATILE_STORAGE |
			BSP_SYSTEM_FEATURE_SOFTWARE_RESET |
			BSP_SYSTEM_FEATURE_RESET_REASON |
			BSP_SYSTEM_FEATURE_DIAGNOSTIC_SINK |
			BSP_SYSTEM_FEATURE_STATUS_INDICATOR,
		BSP_VECTOR_MINI_ST_PARAMETER_STORAGE_CAPACITY_BYTES,
		BSP_VECTOR_MINI_ST_FLASH_ERASE_SIZE_BYTES,
		BSP_VECTOR_MINI_ST_FLASH_PROGRAM_ALIGNMENT_BYTES
	}
};
