#ifndef CORE_APPLICATION_CONTRACTS_MOTOR_CONFIGURATION_PORT_H
#define CORE_APPLICATION_CONTRACTS_MOTOR_CONFIGURATION_PORT_H

#include <stdbool.h>

typedef enum
{
	MOTOR_PARAMETER_POLE_PAIRS = 0,
	MOTOR_PARAMETER_CALIBRATION_CURRENT_A,
	MOTOR_PARAMETER_CURRENT_LIMIT_A,
	MOTOR_PARAMETER_SPEED_LIMIT_RAD_S,
	MOTOR_PARAMETER_SPEED_ACCELERATION_RAD_S2,
	MOTOR_PARAMETER_SPEED_DECELERATION_RAD_S2,
	MOTOR_PARAMETER_SPEED_KP,
	MOTOR_PARAMETER_SPEED_KI,
	MOTOR_PARAMETER_POSITION_ACCELERATION_RAD_S2,
	MOTOR_PARAMETER_POSITION_DECELERATION_RAD_S2,
	MOTOR_PARAMETER_POSITION_MAX_SPEED_RAD_S,
	MOTOR_PARAMETER_POSITION_KP_A_PER_RAD,
	MOTOR_PARAMETER_POSITION_KD_A_PER_RAD_S,
	MOTOR_PARAMETER_POSITION_KI_A_PER_RAD_S,
	MOTOR_PARAMETER_POSITION_INTEGRAL_LIMIT_A,
	MOTOR_PARAMETER_CASCADE_POSITION_KP_PER_S,
	MOTOR_PARAMETER_CASCADE_POSITION_KD,
	MOTOR_PARAMETER_PHASE_RESISTANCE_OHM,
	MOTOR_PARAMETER_D_AXIS_INDUCTANCE_H,
	MOTOR_PARAMETER_Q_AXIS_INDUCTANCE_H,
	MOTOR_PARAMETER_FLUX_WEBER
} MotorParameterId;

typedef struct
{
	void *context;
	bool (*can_stage)(void *context);
	bool (*read)(void *context, MotorParameterId parameter, float *value);
	bool (*stage)(void *context, MotorParameterId parameter, float value);
} MotorConfigurationPort;

#endif
