#ifndef CONTROL_CONFIG_H
#define CONTROL_CONFIG_H

#include "motor_hardware_profile.h"

/* 控制时基、RTT 遥测、无感启动与编码器标定默认参数契约。
 * platform/api 层拥有该契约；板级配置（hw_conf.h）引用并据此派生定时器参数，
 * motor 层算法直接包含本头文件。 */

/* 控制时基契约：电流环频率由控制层定义，板级定时器据此配置。 */
#define FOC_FREQ 20000U
#define FOC_PERIOD (1.0f / (float)FOC_FREQ)

/* Current loop executes at the PWM/FOC rate. */
#define Current_Ts (FOC_PERIOD)

/* All speed PI controllers and encoder velocity estimation run at 2 kHz. */
#define SPEED_LOOP_FREQ 2000U
#if SPEED_LOOP_FREQ == 0U
#error "SPEED_LOOP_FREQ must be greater than zero"
#elif SPEED_LOOP_FREQ > FOC_FREQ
#error "SPEED_LOOP_FREQ must not exceed FOC_FREQ"
#elif (FOC_FREQ % SPEED_LOOP_FREQ) != 0U
#error "SPEED_LOOP_FREQ must divide FOC_FREQ exactly"
#endif
#define SPEED_LOOP_DIVIDER (FOC_FREQ / SPEED_LOOP_FREQ)
#define Speed_Ts (1.0f / (float)SPEED_LOOP_FREQ)

/* Position trajectory and impedance controller run at 2 kHz. */
#define POSITION_LOOP_FREQ 2000U
#if POSITION_LOOP_FREQ == 0U
#error "POSITION_LOOP_FREQ must be greater than zero"
#elif POSITION_LOOP_FREQ > FOC_FREQ
#error "POSITION_LOOP_FREQ must not exceed FOC_FREQ"
#elif (FOC_FREQ % POSITION_LOOP_FREQ) != 0U
#error "POSITION_LOOP_FREQ must divide FOC_FREQ exactly"
#endif
#define POSITION_LOOP_DIVIDER (FOC_FREQ / POSITION_LOOP_FREQ)
#define Position_Ts (1.0f / (float)POSITION_LOOP_FREQ)

/* Legacy cascaded position and trajectory controller also run at 2 kHz. */
#define CASCADE_POSITION_LOOP_FREQ 2000U
#if CASCADE_POSITION_LOOP_FREQ == 0U
#error "CASCADE_POSITION_LOOP_FREQ must be greater than zero"
#elif CASCADE_POSITION_LOOP_FREQ > FOC_FREQ
#error "CASCADE_POSITION_LOOP_FREQ must not exceed FOC_FREQ"
#elif (FOC_FREQ % CASCADE_POSITION_LOOP_FREQ) != 0U
#error "CASCADE_POSITION_LOOP_FREQ must divide FOC_FREQ exactly"
#endif
#define CASCADE_POSITION_LOOP_DIVIDER (FOC_FREQ / CASCADE_POSITION_LOOP_FREQ)
#define Cascade_Position_Ts (1.0f / (float)CASCADE_POSITION_LOOP_FREQ)

/* Sensorless speed-mode startup and observer handoff. */
#define SENSORLESS_ALIGN_CURRENT_RAMP_TIME_S 0.50f
#define SENSORLESS_ALIGN_HOLD_TIME_S 0.30f
#define SENSORLESS_ALIGN_CURRENT_A 2.0f
#define SENSORLESS_STARTUP_IQ_INITIAL_A 0.15f
#define SENSORLESS_STARTUP_IQ_A 0.50f
#define SENSORLESS_STARTUP_IQ_RAMP_TIME_S 2.00f
#define SENSORLESS_STARTUP_ID_A 0.5f
#define SENSORLESS_STARTUP_MIN_ELEC_VEL_RAD_S 250.0f
#define SENSORLESS_STARTUP_TARGET_ELEC_VEL_RAD_S 420.0f
#define SENSORLESS_STARTUP_RAMP_TIME_S 2.00f
#define SENSORLESS_STARTUP_SPEED_LOCK_TIME_S 0.20f
#define SENSORLESS_SPEED_LOCK_FILTER_ALPHA 1.0f
#define SENSORLESS_OBSERVER_LOCK_RATIO 0.25f
#define SENSORLESS_ANGLE_HANDOFF_TIME_S 0.10f
#define SENSORLESS_STARTUP_LOCK_TIMEOUT_S 3.00f
#define SENSORLESS_ID_RAMP_DOWN_TIME_S 0.50f
#define SENSORLESS_OBSERVER_LOSS_TIME_S 0.20f
#define SENSORLESS_OBSERVER_MAX_ELEC_VEL_RAD_S 5000.0f
#define SENSORLESS_SPEED_FEEDBACK_LPF_ALPHA 0.1042f

/* 编码器标定（Mode 13 观测器 LUT / Mode 15 电角度零位）默认参数契约。
 * 与无感启动共用同一配置结构；装配差异由 motor_hardware_profile.h 的
 * 阻尼环选择投影，标定模块只消费本契约。 */
#if MOTOR_HAS_DAMPING_RING == MOTOR_DAMPING_RING_ENABLED
#define SENSORLESS_ENCODER_CALIB_ALIGN_CURRENT_RAMP_TIME_S 0.80f
#define SENSORLESS_ENCODER_CALIB_ALIGN_HOLD_TIME_S 0.50f
#define SENSORLESS_ENCODER_CALIB_ALIGN_CURRENT_A 3.5f
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_INITIAL_A 3.5f
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_A 4.5f
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_RAMP_TIME_S 1.00f
#define SENSORLESS_ENCODER_CALIB_STARTUP_ID_A 0.5f
#define SENSORLESS_ENCODER_CALIB_MIN_CURRENT_LIMIT_A 5.5f
#define SENSORLESS_ENCODER_CALIB_MIN_ELEC_VEL_RAD_S 250.0f
#define SENSORLESS_ENCODER_CALIB_TARGET_ELEC_VEL_RAD_S 420.0f
#define SENSORLESS_ENCODER_CALIB_SPEED_MEC_RAD_S 20.0f
#define SENSORLESS_ENCODER_CALIB_STARTUP_RAMP_TIME_S 2.00f
#define SENSORLESS_ENCODER_CALIB_SPEED_LOCK_TIME_S 0.20f
#define SENSORLESS_ENCODER_CALIB_SPEED_LOCK_FILTER_ALPHA 0.01f
#define SENSORLESS_ENCODER_CALIB_OBSERVER_LOCK_RATIO 0.25f
#define SENSORLESS_ENCODER_CALIB_ANGLE_HANDOFF_TIME_S 0.10f
#define SENSORLESS_ENCODER_CALIB_LOCK_TIMEOUT_S 5.00f
#define SENSORLESS_ENCODER_CALIB_ID_RAMP_DOWN_TIME_S 0.50f
#define SENSORLESS_ENCODER_CALIB_OBSERVER_LOSS_TIME_S 0.20f
#define SENSORLESS_ENCODER_CALIB_SPEED_STABLE_TIMEOUT_S 10.00f
#define SENSORLESS_ENCODER_CALIB_MECH_TURNS 5U
#define SENSORLESS_ENCODER_CALIB_STARTUP_TIMEOUT_S 12.0f
#define SENSORLESS_ENCODER_CALIB_STOP_CURRENT_RAMP_TIME_S 0.10f
#define ENCODER_ELEC_ZERO_MIN_ALIGN_CURRENT_A 4.5f
#elif MOTOR_HAS_DAMPING_RING == MOTOR_DAMPING_RING_DISABLED
#define SENSORLESS_ENCODER_CALIB_ALIGN_CURRENT_RAMP_TIME_S SENSORLESS_ALIGN_CURRENT_RAMP_TIME_S
#define SENSORLESS_ENCODER_CALIB_ALIGN_HOLD_TIME_S SENSORLESS_ALIGN_HOLD_TIME_S
#define SENSORLESS_ENCODER_CALIB_ALIGN_CURRENT_A SENSORLESS_ALIGN_CURRENT_A
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_INITIAL_A SENSORLESS_STARTUP_IQ_INITIAL_A
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_A SENSORLESS_STARTUP_IQ_A
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_RAMP_TIME_S SENSORLESS_STARTUP_IQ_RAMP_TIME_S
#define SENSORLESS_ENCODER_CALIB_STARTUP_ID_A SENSORLESS_STARTUP_ID_A
#define SENSORLESS_ENCODER_CALIB_MIN_CURRENT_LIMIT_A 0.0f
#define SENSORLESS_ENCODER_CALIB_MIN_ELEC_VEL_RAD_S SENSORLESS_STARTUP_MIN_ELEC_VEL_RAD_S
/* 21-pole-pair, unloaded motor: steady calibration target is about 143 rpm.
 * Handoff transients and normal wheel speed limits are separate. */
#define SENSORLESS_ENCODER_CALIB_TARGET_ELEC_VEL_RAD_S 315.0f
#define SENSORLESS_ENCODER_CALIB_SPEED_MEC_RAD_S 15.0f
#define SENSORLESS_ENCODER_CALIB_STARTUP_RAMP_TIME_S SENSORLESS_STARTUP_RAMP_TIME_S
#define SENSORLESS_ENCODER_CALIB_SPEED_LOCK_TIME_S SENSORLESS_STARTUP_SPEED_LOCK_TIME_S
#define SENSORLESS_ENCODER_CALIB_SPEED_LOCK_FILTER_ALPHA SENSORLESS_SPEED_LOCK_FILTER_ALPHA
#define SENSORLESS_ENCODER_CALIB_OBSERVER_LOCK_RATIO SENSORLESS_OBSERVER_LOCK_RATIO
#define SENSORLESS_ENCODER_CALIB_ANGLE_HANDOFF_TIME_S SENSORLESS_ANGLE_HANDOFF_TIME_S
#define SENSORLESS_ENCODER_CALIB_LOCK_TIMEOUT_S SENSORLESS_STARTUP_LOCK_TIMEOUT_S
#define SENSORLESS_ENCODER_CALIB_ID_RAMP_DOWN_TIME_S SENSORLESS_ID_RAMP_DOWN_TIME_S
#define SENSORLESS_ENCODER_CALIB_OBSERVER_LOSS_TIME_S SENSORLESS_OBSERVER_LOSS_TIME_S
#define SENSORLESS_ENCODER_CALIB_SPEED_STABLE_TIMEOUT_S 5.00f
#define SENSORLESS_ENCODER_CALIB_MECH_TURNS 10U
#define SENSORLESS_ENCODER_CALIB_STARTUP_TIMEOUT_S 8.0f
#define SENSORLESS_ENCODER_CALIB_STOP_CURRENT_RAMP_TIME_S 0.50f
#define ENCODER_ELEC_ZERO_MIN_ALIGN_CURRENT_A 0.0f
#else
#error "MOTOR_HAS_DAMPING_RING must be MOTOR_DAMPING_RING_ENABLED or MOTOR_DAMPING_RING_DISABLED"
#endif

/* 编码器标定公共阈值（与装配无关）。 */
#define SENSORLESS_ENCODER_CALIB_SPEED_ERROR_RATIO 0.20f
#define SENSORLESS_ENCODER_CALIB_SPEED_STABLE_TIME_S 0.50f
#define SENSORLESS_ENCODER_CALIB_ALIGN_SAMPLE_TIME_S 0.10f
#define SENSORLESS_ENCODER_CALIB_VERIFY_MECH_TURNS 1U
#define SENSORLESS_ENCODER_CALIB_MIN_SAMPLES_PER_BIN 16U
#define SENSORLESS_ENCODER_CALIB_LUT_BUILD_BINS_PER_CYCLE 8U
#define SENSORLESS_ENCODER_CALIB_FIND_ORIGIN_TIMEOUT_S 1.50f
#define SENSORLESS_ENCODER_CALIB_SAMPLE_TIMEOUT_S 12.00f
#define SENSORLESS_ENCODER_CALIB_VERIFY_TIMEOUT_S 4.00f
#define SENSORLESS_ENCODER_CALIB_MAX_RMS_RESIDUAL_Q15 256U
#define SENSORLESS_ENCODER_CALIB_MAX_PEAK_RESIDUAL_Q15 1024U
#define SENSORLESS_ENCODER_CALIB_STOP_SPEED_MARGIN 1.05f
#define SENSORLESS_ENCODER_CALIB_STOP_DECEL_TIME_S 1.00f
#define SENSORLESS_ENCODER_CALIB_STOP_DECEL_TIMEOUT_S 3.00f
#define SENSORLESS_ENCODER_CALIB_STOP_SPEED_TOLERANCE_RATIO 0.10f

/* 电角度零位对齐时序（Mode 15）。 */
#define ENCODER_ELEC_ZERO_CURRENT_RAMP_TIME_S 0.50f
#define ENCODER_ELEC_ZERO_HOLD_TIME_S 1.00f

/* RTT 遥测契约：上行 channel 1，采样频率必须整除 FOC_FREQ。 */
#define RTT_SAMPLE_RATE_HZ 2000U
#if RTT_SAMPLE_RATE_HZ == 0U
#error "RTT_SAMPLE_RATE_HZ must be greater than zero"
#elif RTT_SAMPLE_RATE_HZ > FOC_FREQ
#error "RTT_SAMPLE_RATE_HZ must not exceed FOC_FREQ"
#elif (FOC_FREQ % RTT_SAMPLE_RATE_HZ) != 0U
#error "RTT_SAMPLE_RATE_HZ must divide FOC_FREQ exactly"
#endif
#define RTT_SAMPLE_DIVIDER (FOC_FREQ / RTT_SAMPLE_RATE_HZ)

/* 固定 4 通道 int16 帧：位置/转速/Iq 指令/Iq 反馈，布局见 rtt_telemetry.c。 */
#define RTT_JSCOPE_DESCRIPTOR "JScope_i2i2i2i2"

#endif
