#ifndef BSP_BOARDS_VECTOR_MINI_ST_BOOTSTRAP_FIRMWARE_COMPOSITION_H
#define BSP_BOARDS_VECTOR_MINI_ST_BOOTSTRAP_FIRMWARE_COMPOSITION_H

void FirmwareComposition_Initialize(void);
void FirmwareComposition_ExecuteFastLoop(void);
void FirmwareComposition_ExecuteSupervisor1kHz(void);
void FirmwareComposition_OnCanReceiveInterrupt(void);
void FirmwareComposition_RunBackground(void);

#endif
