#ifndef CORE_APPLICATION_PROCEDURE_STATE_H
#define CORE_APPLICATION_PROCEDURE_STATE_H

typedef enum
{
	PROCEDURE_STATE_IDLE = 0,
	PROCEDURE_STATE_PRECHECK,
	PROCEDURE_STATE_RUNNING,
	PROCEDURE_STATE_VERIFYING,
	PROCEDURE_STATE_COMPLETED,
	PROCEDURE_STATE_FAILED,
	PROCEDURE_STATE_CANCELLED
} ProcedureState;

#endif
