#ifndef __POSITION_IMPEDANCE_CONFIG_H__
#define __POSITION_IMPEDANCE_CONFIG_H__

/* Public parameter bounds. */
#define POSITION_IMPEDANCE_KP_MAX_A_PER_RAD       50.0f
#define POSITION_IMPEDANCE_KD_MAX_A_PER_RAD_S     10.0f
#define POSITION_IMPEDANCE_KI_MAX_A_PER_RAD_S     10.0f
#define POSITION_IMPEDANCE_MAX_SPEED_RPS          0.125f

/* Internal shaping for the low-speed (8 s/rev) controller. */
#define POSITION_IMPEDANCE_VELOCITY_FILTER_HZ     20.0f
#define POSITION_IMPEDANCE_INTEGRAL_ZONE_RAD      0.08726646f /* 5 deg */
#define POSITION_IMPEDANCE_INTEGRAL_SPEED_RAD_S   0.03f
#define POSITION_IMPEDANCE_INTEGRAL_DECAY_DISTANCE_RAD       0.08726646f /* 5 deg */
#define POSITION_IMPEDANCE_INTEGRAL_DECAY_MIN_SPEED_RAD_S    0.02f
#define POSITION_IMPEDANCE_INTEGRAL_OPPOSING_DECAY_RATIO_PER_TICK 0.01f
#define POSITION_IMPEDANCE_INTEGRAL_DECAY_MAX_RATIO_PER_TICK 0.01f
#define POSITION_IMPEDANCE_INTEGRAL_DECAY_MAX_STEP_A         0.005f
#define POSITION_IMPEDANCE_INTEGRAL_ZERO_THRESHOLD_A         0.0005f
#define POSITION_IMPEDANCE_HOLD_ENTER_SPEED_RAD_S 0.03f
#define POSITION_IMPEDANCE_HOLD_EXIT_SPEED_RAD_S  0.08f
#define POSITION_IMPEDANCE_HOLD_TIME_S            0.05f

#endif
