#ifndef __POSITION_IMPEDANCE_CONFIG_H__
#define __POSITION_IMPEDANCE_CONFIG_H__

#include "hw_conf.h"

/* Public parameter bounds. */
#define POSITION_IMPEDANCE_KP_MAX_A_PER_RAD       50.0f
#define POSITION_IMPEDANCE_KD_MAX_A_PER_RAD_S     10.0f
#define POSITION_IMPEDANCE_KI_MAX_A_PER_RAD_S     10.0f
#define POSITION_IMPEDANCE_MAX_SPEED_RPS          0.50f

/* Internal shaping for the low-speed (8 s/rev) controller. */
#define POSITION_IMPEDANCE_VELOCITY_FILTER_HZ     20.0f
#define POSITION_IMPEDANCE_INTEGRAL_ZONE_RAD      0.08726646f /* 5 deg */
#define POSITION_IMPEDANCE_INTEGRAL_SPEED_RAD_S   0.03f
#define POSITION_IMPEDANCE_INTEGRAL_DECAY_DISTANCE_RAD       0.08726646f /* 5 deg */
#define POSITION_IMPEDANCE_INTEGRAL_DECAY_MIN_SPEED_RAD_S    0.02f
#define POSITION_IMPEDANCE_INTEGRAL_OPPOSING_DECAY_RATIO_PER_TICK 0.01f
#define POSITION_IMPEDANCE_INTEGRAL_DECAY_MAX_RATIO_PER_TICK 0.01f
#define POSITION_IMPEDANCE_INTEGRAL_DECAY_MAX_STEP_A         0.005f
#define POSITION_IMPEDANCE_INTEGRAL_ZERO_THRESHOLD_A         0.0005f
#define POSITION_IMPEDANCE_HOLD_ENTER_SPEED_RAD_S 0.03f
#define POSITION_IMPEDANCE_HOLD_EXIT_SPEED_RAD_S  0.08f
#define POSITION_IMPEDANCE_HOLD_TIME_S            0.05f

/*
 * Damping-ring friction compensation, identified from the 01_position-loop_03
 * capture. Positive and negative values are magnitudes; direction is selected
 * from the continuous target error and trajectory velocity.
 */
#if MOTOR_DAMPING_FEEDFORWARD == MOTOR_DAMPING_FEEDFORWARD_ENABLED
#define POSITION_IMPEDANCE_FRICTION_POSITIVE_A            1.55f
#define POSITION_IMPEDANCE_FRICTION_NEGATIVE_A            1.50f
#define POSITION_IMPEDANCE_BREAKAWAY_POSITIVE_A           1.85f
#define POSITION_IMPEDANCE_BREAKAWAY_NEGATIVE_A           1.80f
#else
#define POSITION_IMPEDANCE_FRICTION_POSITIVE_A            0.0f
#define POSITION_IMPEDANCE_FRICTION_NEGATIVE_A            0.0f
#define POSITION_IMPEDANCE_BREAKAWAY_POSITIVE_A           0.0f
#define POSITION_IMPEDANCE_BREAKAWAY_NEGATIVE_A           0.0f
#endif
#define POSITION_IMPEDANCE_FRICTION_CURRENT_SLEW_A_PER_S 15.0f
#define POSITION_IMPEDANCE_FRICTION_POSITION_ENTER_RAD    0.001f
#define POSITION_IMPEDANCE_FRICTION_POSITION_EXIT_RAD     0.003f
#define POSITION_IMPEDANCE_FRICTION_REFERENCE_SPEED_RAD_S 0.03f
#define POSITION_IMPEDANCE_FRICTION_STOP_SPEED_RAD_S      0.02f
#define POSITION_IMPEDANCE_FRICTION_MOVE_SPEED_RAD_S      0.05f
#define POSITION_IMPEDANCE_FRICTION_STUCK_TIME_S          0.05f
#define POSITION_IMPEDANCE_FRICTION_LANDING_POSITION_RAD  0.006f
#define POSITION_IMPEDANCE_FRICTION_LANDING_SPEED_RAD_S   0.10f
#define POSITION_IMPEDANCE_FRICTION_RECOVERY_DELAY_S      0.20f
#define POSITION_IMPEDANCE_FRICTION_RECOVERY_PULSE_S      0.05f
#define POSITION_IMPEDANCE_FRICTION_RECOVERY_COOLDOWN_S   0.20f

#endif
