#ifndef __HW_CONF_H__
#define __HW_CONF_H__

#include "main.h"
#include "current_sense_profile.h"

#define PWM_TIM_CLOCK			170000000
#define PWM_TIM_FREQ			20000 /*Hz*/
#define PWM_TIM_PERIOD			(PWM_TIM_CLOCK / PWM_TIM_FREQ / 2)	
#define PWM_PERIOD				5e-5f

#define FOC_FREQ				PWM_TIM_FREQ
#define FOC_PERIOD				(1.0f / (float)FOC_FREQ)

/*RTT output sampling frequency; must divide FOC_FREQ exactly*/
#define RTT_SAMPLE_RATE_HZ		2000U

#if RTT_SAMPLE_RATE_HZ == 0U
#error "RTT_SAMPLE_RATE_HZ must be greater than zero"
#elif RTT_SAMPLE_RATE_HZ > FOC_FREQ
#error "RTT_SAMPLE_RATE_HZ must not exceed FOC_FREQ"
#elif (FOC_FREQ % RTT_SAMPLE_RATE_HZ) != 0U
#error "RTT_SAMPLE_RATE_HZ must divide FOC_FREQ exactly"
#endif

#define RTT_SAMPLE_DIVIDER		(FOC_FREQ / RTT_SAMPLE_RATE_HZ)

/* Three-phase low-side current sensing; selected in current_sense_profile.h. */
#define SENSING_RES                         CURRENT_SENSE_PROFILE_SHUNT_RESISTANCE_OHM
#define CURRENT_AMP_GAIN                    CURRENT_SENSE_PROFILE_AMPLIFIER_GAIN
/* Current represented by one 12-bit ADC count (A/count). */
#define SENSING_CURR_FACTOR                 (float)(3.3f / 4095.0f / CURRENT_AMP_GAIN / SENSING_RES)

/* Keep normal control and software protection below the amplifier/ADC rails. */
#define CURRENT_SENSE_RELIABLE_LIMIT_A      CURRENT_SENSE_PROFILE_RELIABLE_LIMIT_A
#define CURRENT_COMMAND_LIMIT_MAX_A         CURRENT_SENSE_PROFILE_COMMAND_LIMIT_MAX_A
#define CURRENT_CALIB_LIMIT_MAX_A           CURRENT_SENSE_PROFILE_CALIB_LIMIT_MAX_A
#define CURRENT_OVERCURRENT_TRIP_A          CURRENT_SENSE_PROFILE_OVERCURRENT_TRIP_A

/*bus voltagge R1 R2 (kohm)*/
#define VBUS_R1					10.0f
#define VBUS_R2					1.0f
/*bus voltage sensing factor (adc value/V)*/
#define SENSING_VBUS_FACTOR    	(float)(3.3f / 4095.0f * (VBUS_R1 + VBUS_R2) / VBUS_R2)

#define TEMP_R2					3.3f

/*MOSFET approximate deadtime (s)*/
#define MOS_DEADTIME			2.1e-7f
/*voltage of body diode (V)*/
#define MOS_VDIODE				0.5f

#define DBC_FACTOR				MOS_DEADTIME / PWM_PERIOD / 1000000000.0f

#define CURRENT_ADC				ADC2
#define IA_ADC_CHANNEL			JDR1
#define IB_ADC_CHANNEL			JDR2
#define IC_ADC_CHANNEL			JDR3

#define VBUS_ADC				ADC2
#define VBUS_ADC_CHANNEL		JDR4

#define TEMP_ADC				ADC1
#define TEMP_ADC_CHANNEL		JDR1

/* Current loop executes at the PWM/FOC rate. */
#define Current_Ts                  (FOC_PERIOD)

/* All speed PI controllers and encoder velocity estimation run at 2 kHz. */
#define SPEED_LOOP_FREQ             2000U
#if SPEED_LOOP_FREQ == 0U
#error "SPEED_LOOP_FREQ must be greater than zero"
#elif SPEED_LOOP_FREQ > FOC_FREQ
#error "SPEED_LOOP_FREQ must not exceed FOC_FREQ"
#elif (FOC_FREQ % SPEED_LOOP_FREQ) != 0U
#error "SPEED_LOOP_FREQ must divide FOC_FREQ exactly"
#endif
#define SPEED_LOOP_DIVIDER          (FOC_FREQ / SPEED_LOOP_FREQ)
#define Speed_Ts                    (1.0f / (float)SPEED_LOOP_FREQ)

/* Position trajectory and impedance controller run at 1 kHz. */
#define POSITION_LOOP_FREQ          1000U
#if POSITION_LOOP_FREQ == 0U
#error "POSITION_LOOP_FREQ must be greater than zero"
#elif POSITION_LOOP_FREQ > FOC_FREQ
#error "POSITION_LOOP_FREQ must not exceed FOC_FREQ"
#elif (FOC_FREQ % POSITION_LOOP_FREQ) != 0U
#error "POSITION_LOOP_FREQ must divide FOC_FREQ exactly"
#endif
#define POSITION_LOOP_DIVIDER       (FOC_FREQ / POSITION_LOOP_FREQ)
#define Position_Ts                 (1.0f / (float)POSITION_LOOP_FREQ)

/* Legacy cascaded position-speed-current controller runs at 5 kHz. */
#define CASCADE_POSITION_LOOP_FREQ  5000U
#if CASCADE_POSITION_LOOP_FREQ == 0U
#error "CASCADE_POSITION_LOOP_FREQ must be greater than zero"
#elif CASCADE_POSITION_LOOP_FREQ > FOC_FREQ
#error "CASCADE_POSITION_LOOP_FREQ must not exceed FOC_FREQ"
#elif (FOC_FREQ % CASCADE_POSITION_LOOP_FREQ) != 0U
#error "CASCADE_POSITION_LOOP_FREQ must divide FOC_FREQ exactly"
#endif
#define CASCADE_POSITION_LOOP_DIVIDER (FOC_FREQ / CASCADE_POSITION_LOOP_FREQ)
#define Cascade_Position_Ts         (1.0f / (float)CASCADE_POSITION_LOOP_FREQ)

/* Sensorless speed-mode startup and observer handoff. */
#define SENSORLESS_ALIGN_CURRENT_RAMP_TIME_S       0.50f
#define SENSORLESS_ALIGN_HOLD_TIME_S               0.30f
#define SENSORLESS_ALIGN_TIME_S                    (SENSORLESS_ALIGN_CURRENT_RAMP_TIME_S + SENSORLESS_ALIGN_HOLD_TIME_S)
#define SENSORLESS_ALIGN_CURRENT_A                  2.0f
#define SENSORLESS_STARTUP_IQ_INITIAL_A             0.15f
#define SENSORLESS_STARTUP_IQ_A                     0.50f
#define SENSORLESS_STARTUP_IQ_RAMP_TIME_S           2.00f
#define SENSORLESS_STARTUP_ID_A                     0.5f
#define SENSORLESS_STARTUP_MIN_ELEC_VEL_RAD_S      250.0f
#define SENSORLESS_STARTUP_TARGET_ELEC_VEL_RAD_S   420.0f
#define SENSORLESS_STARTUP_RAMP_TIME_S             2.00f
#define SENSORLESS_STARTUP_ELEC_ACCEL_RAD_S2       (SENSORLESS_STARTUP_TARGET_ELEC_VEL_RAD_S / SENSORLESS_STARTUP_RAMP_TIME_S)
#define SENSORLESS_STARTUP_SPEED_LOCK_TIME_S       0.20f
#define SENSORLESS_SPEED_LOCK_FILTER_ALPHA          1.0f
#define SENSORLESS_OBSERVER_LOCK_RATIO             0.25f
#define SENSORLESS_ANGLE_HANDOFF_TIME_S            0.10f
#define SENSORLESS_STARTUP_LOCK_TIMEOUT_S          3.00f
#define SENSORLESS_ID_RAMP_DOWN_TIME_S             0.50f
#define SENSORLESS_OBSERVER_LOSS_TIME_S            0.20f
#define SENSORLESS_OBSERVER_MAX_ELEC_VEL_RAD_S     5000.0f
#define SENSORLESS_SPEED_FEEDBACK_LPF_ALPHA         0.1042f

/* Damping-ring dependent encoder calibration profile. */
#define MOTOR_DAMPING_RING_DISABLED                         0U
#define MOTOR_DAMPING_RING_ENABLED                          1U
#ifndef MOTOR_HAS_DAMPING_RING
#define MOTOR_HAS_DAMPING_RING              MOTOR_DAMPING_RING_ENABLED
#endif

/*
 * Position-impedance damping/friction feedforward. This is intentionally
 * independent from MOTOR_HAS_DAMPING_RING so calibration can retain the
 * damping-ring startup profile while the feedforward controller is disabled.
 */
#define MOTOR_DAMPING_FEEDFORWARD_DISABLED                  0U
#define MOTOR_DAMPING_FEEDFORWARD_ENABLED                   1U
#ifndef MOTOR_DAMPING_FEEDFORWARD
#define MOTOR_DAMPING_FEEDFORWARD           MOTOR_HAS_DAMPING_RING
#endif

#if MOTOR_DAMPING_FEEDFORWARD != MOTOR_DAMPING_FEEDFORWARD_ENABLED && \
	MOTOR_DAMPING_FEEDFORWARD != MOTOR_DAMPING_FEEDFORWARD_DISABLED
#error "MOTOR_DAMPING_FEEDFORWARD must be MOTOR_DAMPING_FEEDFORWARD_ENABLED or MOTOR_DAMPING_FEEDFORWARD_DISABLED"
#endif

#if MOTOR_HAS_DAMPING_RING == MOTOR_DAMPING_RING_ENABLED
#define SENSORLESS_ENCODER_CALIB_ALIGN_CURRENT_RAMP_TIME_S 0.80f
#define SENSORLESS_ENCODER_CALIB_ALIGN_HOLD_TIME_S         0.50f
#define SENSORLESS_ENCODER_CALIB_ALIGN_CURRENT_A           3.5f
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_INITIAL_A      3.5f
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_A              4.5f
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_RAMP_TIME_S    1.00f
#define SENSORLESS_ENCODER_CALIB_STARTUP_ID_A              0.5f
#define SENSORLESS_ENCODER_CALIB_MIN_CURRENT_LIMIT_A       5.5f
#define SENSORLESS_ENCODER_CALIB_MIN_ELEC_VEL_RAD_S       250.0f
#define SENSORLESS_ENCODER_CALIB_TARGET_ELEC_VEL_RAD_S    420.0f
#define SENSORLESS_ENCODER_CALIB_STARTUP_RAMP_TIME_S       2.00f
#define SENSORLESS_ENCODER_CALIB_SPEED_LOCK_TIME_S         0.20f
#define SENSORLESS_ENCODER_CALIB_SPEED_LOCK_FILTER_ALPHA   0.01f
#define SENSORLESS_ENCODER_CALIB_OBSERVER_LOCK_RATIO       0.25f
#define SENSORLESS_ENCODER_CALIB_ANGLE_HANDOFF_TIME_S      0.10f
#define SENSORLESS_ENCODER_CALIB_LOCK_TIMEOUT_S            5.00f
#define SENSORLESS_ENCODER_CALIB_ID_RAMP_DOWN_TIME_S       0.50f
#define SENSORLESS_ENCODER_CALIB_OBSERVER_LOSS_TIME_S      0.20f
#define SENSORLESS_ENCODER_CALIB_SPEED_STABLE_TIMEOUT_S   10.00f
#define SENSORLESS_ENCODER_CALIB_MECH_TURNS                5U
#define SENSORLESS_ENCODER_CALIB_STARTUP_TIMEOUT_S        12.0f
#define SENSORLESS_ENCODER_CALIB_STOP_CURRENT_RAMP_TIME_S  0.10f
#define ENCODER_ELEC_ZERO_MIN_ALIGN_CURRENT_A              4.5f
#elif MOTOR_HAS_DAMPING_RING == MOTOR_DAMPING_RING_DISABLED
#define SENSORLESS_ENCODER_CALIB_ALIGN_CURRENT_RAMP_TIME_S SENSORLESS_ALIGN_CURRENT_RAMP_TIME_S
#define SENSORLESS_ENCODER_CALIB_ALIGN_HOLD_TIME_S         SENSORLESS_ALIGN_HOLD_TIME_S
#define SENSORLESS_ENCODER_CALIB_ALIGN_CURRENT_A           SENSORLESS_ALIGN_CURRENT_A
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_INITIAL_A      SENSORLESS_STARTUP_IQ_INITIAL_A
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_A              SENSORLESS_STARTUP_IQ_A
#define SENSORLESS_ENCODER_CALIB_STARTUP_IQ_RAMP_TIME_S    SENSORLESS_STARTUP_IQ_RAMP_TIME_S
#define SENSORLESS_ENCODER_CALIB_STARTUP_ID_A              SENSORLESS_STARTUP_ID_A
#define SENSORLESS_ENCODER_CALIB_MIN_CURRENT_LIMIT_A       0.0f
#define SENSORLESS_ENCODER_CALIB_MIN_ELEC_VEL_RAD_S        SENSORLESS_STARTUP_MIN_ELEC_VEL_RAD_S
#define SENSORLESS_ENCODER_CALIB_TARGET_ELEC_VEL_RAD_S     SENSORLESS_STARTUP_TARGET_ELEC_VEL_RAD_S
#define SENSORLESS_ENCODER_CALIB_STARTUP_RAMP_TIME_S       SENSORLESS_STARTUP_RAMP_TIME_S
#define SENSORLESS_ENCODER_CALIB_SPEED_LOCK_TIME_S         SENSORLESS_STARTUP_SPEED_LOCK_TIME_S
#define SENSORLESS_ENCODER_CALIB_SPEED_LOCK_FILTER_ALPHA   SENSORLESS_SPEED_LOCK_FILTER_ALPHA
#define SENSORLESS_ENCODER_CALIB_OBSERVER_LOCK_RATIO       SENSORLESS_OBSERVER_LOCK_RATIO
#define SENSORLESS_ENCODER_CALIB_ANGLE_HANDOFF_TIME_S      SENSORLESS_ANGLE_HANDOFF_TIME_S
#define SENSORLESS_ENCODER_CALIB_LOCK_TIMEOUT_S            SENSORLESS_STARTUP_LOCK_TIMEOUT_S
#define SENSORLESS_ENCODER_CALIB_ID_RAMP_DOWN_TIME_S       SENSORLESS_ID_RAMP_DOWN_TIME_S
#define SENSORLESS_ENCODER_CALIB_OBSERVER_LOSS_TIME_S      SENSORLESS_OBSERVER_LOSS_TIME_S
#define SENSORLESS_ENCODER_CALIB_SPEED_STABLE_TIMEOUT_S    5.00f
#define SENSORLESS_ENCODER_CALIB_MECH_TURNS               10U
#define SENSORLESS_ENCODER_CALIB_STARTUP_TIMEOUT_S         8.0f
#define SENSORLESS_ENCODER_CALIB_STOP_CURRENT_RAMP_TIME_S  0.50f
#define ENCODER_ELEC_ZERO_MIN_ALIGN_CURRENT_A              0.0f
#else
#error "MOTOR_HAS_DAMPING_RING must be MOTOR_DAMPING_RING_ENABLED or MOTOR_DAMPING_RING_DISABLED"
#endif

#define SENSORLESS_ENCODER_CALIB_SPEED_MEC_RAD_S           20.0f
#define SENSORLESS_ENCODER_CALIB_SPEED_ERROR_RATIO         0.20f
#define SENSORLESS_ENCODER_CALIB_SPEED_STABLE_TIME_S       0.50f
#define SENSORLESS_ENCODER_CALIB_ALIGN_SAMPLE_TIME_S       0.10f
#define SENSORLESS_ENCODER_CALIB_VERIFY_MECH_TURNS         1U
#define SENSORLESS_ENCODER_CALIB_MIN_SAMPLES_PER_BIN       16U
#define SENSORLESS_ENCODER_CALIB_LUT_BUILD_BINS_PER_CYCLE   8U
#define SENSORLESS_ENCODER_CALIB_FIND_ORIGIN_TIMEOUT_S     1.50f
#define SENSORLESS_ENCODER_CALIB_SAMPLE_TIMEOUT_S         12.00f
#define SENSORLESS_ENCODER_CALIB_VERIFY_TIMEOUT_S          4.00f
#define SENSORLESS_ENCODER_CALIB_MAX_RMS_RESIDUAL_Q15      256U
#define SENSORLESS_ENCODER_CALIB_MAX_PEAK_RESIDUAL_Q15     1024U
#define SENSORLESS_ENCODER_CALIB_STOP_SPEED_MARGIN         1.05f
#define SENSORLESS_ENCODER_CALIB_STOP_DECEL_TIME_S         1.00f
#define SENSORLESS_ENCODER_CALIB_STOP_DECEL_TIMEOUT_S      3.00f
#define SENSORLESS_ENCODER_CALIB_STOP_SPEED_TOLERANCE_RATIO 0.10f

/* Encoder electrical-zero alignment. */
#define ENCODER_ELEC_ZERO_CURRENT_RAMP_TIME_S              0.50f
#define ENCODER_ELEC_ZERO_HOLD_TIME_S                      1.00f

#endif
